---
- name: Provision and Build Oracle Database Standalone Instance
  hosts: oracle_servers
  become: yes
  become_user: oracle
  vars:
    oracle_version: "19c"
    oracle_db_name: "your_db_name"
    oracle_db_template: "General_Purpose.dbc"
    oracle_db_password: "your_db_password"
    oracle_listener_port: 1521
    oracle_db_characterset: "AL32UTF8"

  tasks:
    - name: Install Oracle Database prereqs
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - oracle-database-preinstall-19c
        - binutils
        - gcc
        - make
        - glibc
        - libaio
        - net-tools
        - smartmontools
        - sysstat

    - name: Create Oracle Database
      shell: |
        dbca -silent -createDatabase \
          -templateName {{ oracle_db_template }} \
          -gdbName {{ oracle_db_name }} \
          -sid {{ oracle_db_name }} \
          -responseFile NO_VALUE \
          -characterSet {{ oracle_db_characterset }} \
          -sysPassword {{ oracle_db_password }} \
          -systemPassword {{ oracle_db_password }} \
          -createAsContainerDatabase false \
          -databaseType MULTIPURPOSE \
          -automaticMemoryManagement false \
          -totalMemory 2048 \
          -storageType FS \
          -datafileDestination "/u01/app/oracle/oradata" \
          -redoLogFileSize 50 \
          -emConfiguration NONE \
          -ignorePreReqs
      register: dbca_output
      failed_when: "'100 percent complete' not in dbca_output.stdout"

    - name: Start Oracle Listener
      shell: |
        lsnrctl start
